
teracy-dev-certs:
  # the node id which certs will provision
  node_id: "0" # 0 by default from teracy-dev-core
  ansible:
    mode: guest # or host to run ansible from the host machine
    install_mode: pip
    version: # ansible guest version
    pip_install_cmd: curl https://bootstrap.pypa.io/2.7/get-pip.py | sudo python
  ca:
    days: 2000 # valid days for the root CA cert
    pkcs1_generated: false # to generate the PKCS#1 *-ca.key from the *-ca-key.pem file
  cert:
    days: 825 # valid days for the owned CA signed cert
    generated: true # enabled by default to generate the owned CA signed cert
  common_name: "%{node_hostname_prefix}.%{node_domain_affix}"
  alt_names:
    - "%{node_hostname_prefix}.%{node_domain_affix}"

  # don't try to change node_template if you don't know what you're going to do
  # node template to be overriden
  node_template:
    _id: "0"
    provisioners:
      - _id: certs-ansible
        type: ansible_local
        name: teracy-dev-certs
        verbose: -vv
        weight: 8
        enabled: true
        playbook: "%{teracy-dev-certs-path}/provisioners/ansible/certs.yaml"
